---
- name: Configure app server
  hosts: app_servers
  remote_user: ubuntu
  become: yes # sudo

  tasks:
  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
  - name: Upload content to web site
    copy:
      content: yah hello from ansible
      dest: /var/www/html/index.html

  - name: Install required system packages for Docker
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true
