---
- name: Configure app server
  hosts: app_servers
  remote_user: ubuntu
  become: yes # sudo

  tasks:

  - name: Install required system packages for Docker
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: run app container
    community.docker.docker_container:
      name: "foo_app"
      image: "patrmitacr.azurecr.io/assignment2app:1.0.0"
      env:
        PORT=3001
        DB_HOSTNAME="{{ hostvars['db1']['ansible_host'] }}"
        DB_PORT=5432
        DB_USERNAME=pete
        DB_PASSWORD=devops
      published_ports:
      - "0.0.0.0:80:3001"
      state: started


    
