name: Foo App CD Pipeline


on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  check-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check condition and skip actions
        run: bash check_deploy.sh


  cd-pipeline:
    needs: check-deploy
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v3
      - name: APT update
        run: sudo apt update

# Install (awscli, terraform, ansible, docker)
      - name: Install awscli
        run: sudo apt install awscli
      - name: Install terraform
        run: |
          terraform_binary_url="https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_$(dpkg --print-architecture).zip"
          curl "$terraform_binary_url" > /tmp/terraform.zip
          unzip /tmp/terraform.zip -d /tmp
          sudo mv /tmp/terraform /usr/local/bin
      - name: Install ansible
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible -y
      - name: Install Docker
        run: |
          sudo apt-get install \
          ca-certificates \
          curl \
          gnupg \
          lsb-release -y
          sudo mkdir -m 0755 -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg


# Copy AWS Credentials to ~/.aws/credentials 
      - name: AWS Credentials set up
        run: |
          mkdir ~/.aws
          cat misc/aws_credentials > ~/.aws/credentials 
      - name: AWS Credentials check
        run: cat ~/.aws/credentials 


# Terraform 
      - name: Terraform  - ec2 instance create
        run: | 
          ls
          cd misc/infra
          yes yes | terraform apply
          cd ..

# Ansible
      - name: Ansible - Create the inventory.yml with ip_address
        run: |
          cd ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          cat ../infra/terraform.tfstate | bash get_public_ips.sh
      - name: Ansible - Set-up db ec2 docker
        run: ansible-playbook db-playbook.yml -i inventory.yml --private-key ../tf_key
      - name: Ansible - Set-up app ec2 dockers
        run: ansible-playbook app-playbook.yml -i inventory.yml --private-key ../tf_key
      - name: Ansible - cd back to root directory
        run: cd ../..
